<?php

namespace GaryBundle\Repository;

/**
 * CancionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CancionRepository extends \Doctrine\ORM\EntityRepository
{
}
