<?php

namespace GaryBundle\Repository;

/**
 * TempoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempoRepository extends \Doctrine\ORM\EntityRepository
{
}
